apiVersion: v1
kind: Service
metadata:
  name: spring-boot-postgres-sample
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: spring-boot-postgres-sample
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
data:
  postgres_user: admin
  postgres_password: c1oudc0w
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-postgres-sample
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-postgres-sample
      version: v1
  template:
    metadata:
      labels:
        app: spring-boot-postgres-sample
        version: v1
    spec:
      containers:
      - name: spring-boot-postgres-sample
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password
          - name: POSTGRES_HOST
            value: postgres.backend-data.svc.cluster.local
        image: feriva22/springboot-sample-postgres-k8s:v1